### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by cossio** [invenia/JLSO.jl#10]
The documentation links in the README:

https://invenia.github.io/JLSO.jl/stable
https://invenia.github.io/JLSO.jl/dev

are not working.

**Comment by oxinabox** [comment]
add its kinda empty anyway.

Very rough summary of how to use

Seems not.
`read` gives you a `JLSO` file.
Indexing into that with strings, causes it to load the content
e.g. `read("foo.jlso")["MyData"]` gets the “MyDataObject” from the `"foo.jlso"` file
`load(“foo.jlso”, “MyData”) does also.

`file = JLSOFile["x"] = foo` adds sets the value of {“x”} to be `foo`,
and then you write it to disk with `write(file)`
`save("myfile", "x"=>foo)` does the same.

I will add that to your issue.

**Comment by rofinn** [comment]
Honestly, we might be better off just having a short guide in the README. I believe the general usage  documentation for this still lives in our internal Checkpoints.jl package. FWIW, the following all have docstrings once you load the package on the REPL (e.g., `JLSO` module, `JLSOFile`, `save`, `load`, `getindex`, `setindex!`). Not the most user friendly documentation, but hopefully it'll be enough to get you started?

**Comment by yakir12** [comment]
At least remove those links from the README.md, so people don't go looking for this issue.

**Comment by oxinabox** [comment]
It actually needs its docs fixed.
It needs a API page added,
because it had its index.md replaced with a symlink to Readme.md (which is something i think is cool to reduce duplication. But you do still need the API from docstring stuff).

Also JLSO has a bunch of intro attached to the modules docstring.
Which needs to be extracted.
Again trying to avoid duplicating that.

https://github.com/invenia/JLSO.jl/blob/f2b9c4c63d82db44555f269f8f66e010797817bf/src/JLSO.jl#L1-L37

**Comment by nickrobinson251** [comment]
solved by #19 :)
